language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.3.1
services:
- docker
before_install:
- docker pull mumuki/mumuki-<RUNNER>-worker
deploy:
  provider: rubygems
  api_key:
    secure: Eqj92sCS/K8sEEpD7SeF0461jZG6WarOUtC/RybOVXafv9ahACmFtOS7gFgqySzzRhch+753bnNxADXTqgz2BQ0GHisDsCexcIKSmmDHUorsrql/DzMWlsHt1lCfGC1JDfZqfEdcym5//8R7WJADlty78NVvomyuMn9Eo6DXmUo=
  gem: mumuki-<RUNNER>-runner
  on:
    tags: true
    repo: mumuki/mumuki-<RUNNER>-runner
